### ISSUE TITLE
Publish on Pypi

### ISSUE THREAD

**Issue by eifinger** [flopp/fritz-switch-profiles#2]
Do you plan on publishing your code as a pip package?

I plan to use it in an [Appdaemon](https://appdaemon.readthedocs.io/en/latest/index.html) App for [Homeassistant](http://home-assistant.io)

**Comment by flopp** [comment]
No plans yet. But why not...

**Comment by eifinger** [comment]
Nice timing :D Today I went ahead and started to implement the needed
changes. I Will test them and provide a pull request

Florian Pigorsch <notifications@github.com> schrieb am So., 9. Sep. 2018,
21:12:

**Comment by eifinger** [comment]
Closed by https://github.com/flopp/fritz-switch-profiles/pull/3
